- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: set fact for this host
      set_fact :
        custom_fact: true
        cacheable: true
